//Copyright timeanddate.com 2005-2014, do not use without permission
Mf=Math.floor;Mr=Math.random;function pf(a,b){do a="0000"+a;while(a.length<b);return a.substring(a.length-b)}function p2(a){return a<10?"0"+a:a}function lim(a,b,c){return Math.max(Math.min(a,c),b)}function dt(){return(new Date).getTime()}function it(a,b){if(a){var c=a.length,d;for(d=0;d<c;d++)b(a[d],d)}}function ia(a,b){if(a)for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])}ph={};
function gx(){function a(a){try{if(c.ActiveXObject)return new ActiveXObject(a)}catch(b){}}var b=null,c=window;try{c.XMLHttpRequest&&(b=new XMLHttpRequest)}catch(d){}b||(b=a("Msxml2.XMLHTTP"));b||(b=a("Microsoft.XMLHTTP"));return b}function gp(a,b,c){if(a)try{return a.open("GET","http://"+document.domain+b,!0),a.onreadystatechange=c,a.send(""),1}catch(d){alert(d)}return 0}
function rs4(a){if(a&&a.readyState==4)if(a.status!==200){errm="rs4:status="+a.status;return}else return a.responseText+"";return!1}function ghj(a){var b={j:""},c=a.indexOf("<script");if(c>=0){var d=a.indexOf(">",c);if(d>=0){var e=a.indexOf("<\/script>",d);e>0&&(b.j+=a.slice(d+1,e),a=a.slice(0,c)+a.slice(e+9))}}b.h=a;return b}function jcb(a,b){var c=gx();return c?(gp(c,a,function(){var a=rs4(c);a&&b(a)}),!0):!1}
function rf(a,b,c,d){iH(a,b);a=Mf(1E3*(c+Mr()*d));setTimeout(function(){location.reload()},a)}function phg(a,b,c){var d=ph[a];d?c(d):jcb(b,function(b){ph[a]=b;c(b)})}function gf(a){var b=document;return b.getElementById?b.getElementById(a):b.all?b.all[a]:null}function cE(a,b,c){var d=document.createElement(a);ia(b,function(a,b){a==="class"?d.className=b:d.setAttribute(a,b)});c&&c.appendChild(d);return d}dce=cE;function hC(a,b){var c=a.className;return c&&(" "+c+" ").indexOf(" "+b+" ")>=0}
function arrclone(a){var b=[],c=a.length,d;for(d=0;d<c;d++)b[d]=a[d];return b}function gebc(a,b){b||(b=document);var c;if(b.getElementsByClassName)return c=b.getElementsByClassName(a),arrclone(c);else{var d=b.firstChild,e=[];if(d){do if(d.nodeType==1&&(d.className&&hC(d,a)&&e.push(d),(c=gebc(a,d)).length))e=e.concat(c);while(d=d.nextSibling)}return arrclone(e)}}function gebn(a,b){b||(b=document);var c=b.getElementsByName(a);return arrclone(c)}
function gebtn(a,b){b||(b=document);var c=b.getElementsByTagName(a);return arrclone(c)}function ih(a,b){if(a)a.innerHTML=b}function iH(a,b){ih(gf(a),b)}function sd(a,b){if(a)a.style.display=b?b==2?"block":"":"none"}function he(a,b){sd(gf(a),b)}function ee(a,b,c){if(a=a[b])a.disabled=!c}function ac(a,b,c){if(a){var d=a.className+" ",e=" "+d,f=e.indexOf(" "+b+" ");if(c){if(f>=0)return;d+=b}else{if(f<0)return;d=d.substring(0,f)+e.substring(f+b.length+1)}a.className=d}}
function po(a){for(var b={x:0,y:a.offsetHeight};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b}function ap(a){var b=0,c=0,d=0;if(a.getBoundingClientRect&&navigator.appVersion.match(/MSIE [3-7]/))c=document.documentElement,a=a.getBoundingClientRect(),b=a.left+c.scrollLeft,c=a.top+c.scrollTop;else for(;a;)gcst(a,"position")=="fixed"&&(d=1),b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;return{x:b,y:c,f:d}}function isdef(a){return a!==void 0}
function ep(a,b){var c=a.style;if(isdef(b.x))c.left=b.x+"px";if(isdef(b.y))c.top=b.y+"px";if(isdef(b.f))c.position=b.f?"fixed":"absolute"}function gcst(a,b){var c=window.getComputedStyle;if(c)return c(a,null).getPropertyValue(b);if(c=a.currentStyle)return c[b]}
function gcs(a,b){var c=window.getComputedStyle,d=function(a,b){var c=/^[0-9\.]+(px)?$/i;if(parseFloat(b)>0){if(c.test(b))return parseInt(b);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b||0;b=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d}else b=0;return b};if(c){if(c=c(a,null))return d(a,c.getPropertyValue(b))}else if(c=a.currentStyle)return c=c[b],b=="height"&&c=="auto"&&(c=a.offsetHeight-gcs(a,"marginTop")-gcs(a,"marginBottom")),d(a,c);
return null}function es(a,b){var c=a.style;if(b.w>0)c.width=b.w+"px";if(b.h>0)c.height=b.h+"px"}function esp(a,b){var c=a.style;if(b.w>0)c.width=b.w+"%";if(b.h>0)c.height=b.h+"%"}function esa(a,b){es(a,b);ep(a,b)}function sw(a){var b=[],c=0;it(a,function(a,e){b[e]=a;var f=a.offsetWidth;f>c&&(c=f)});it(b,function(a){es(a,{w:c})})}
function jp(a,b,c,d,e){var f=b.offsetWidth,g=c.offsetWidth,c=c.offsetHeight;d<-1E3&&(a.x+=d+1E3,d=-1);d==-1&&(a.x-=f-g);d==1&&(a.x+=g);d==2&&(a.x+=(g-f)/2);e==-1&&(a.y-=c);e==1&&(a.y+=c);e==2&&(a.y+=(c-b.offsetHeight)/2);if(a.x<0)a.x=0}
function siv(a,b,c,d){var e=document.documentElement,f=0,g=0,h=0,j=c!==void 0?c:1E3,n=d!==void 0?n:function(a){return a==1?1:1-Math.pow(2,-10*a)},c=function(){function a(c){c-=b;c>=j?i(1):h===e.scrollTop?(i(c/j),raf(a)):i(1)}var b=pn();raf(a)},i=function(a){a=n(a);h=Mf(g+(f-g)*a);e.scrollTop=h},d=ap(a);if(d.y+a.clientHeight>e.scrollTop+e.clientHeight||b)f=b?d.y-30:Math.min(d.y-e.clientHeight+a.clientHeight,d.y-30),g=h=e.scrollTop,c()}
function gsv(){var a=document.documentElement,a={w:window.innerWidth||document.body.clientWidth,h:document.height||document.body.scrollHeight,W:a?a.clientWidth:980,H:a?a.clientHeight:600};if(a.H>a.h)a.h=a.H;return a}function wl(a){var b=window.location;if(a)b.href=a;return b}function gso(a){return a.options[a.selectedIndex]}
function gfv(a){var b=a.type;if(b)switch(b){case "select-one":return gso(a).value;case "radio":if(a.checked)return a.value;break;case "checkbox":return a.checked?a.value:"";case "button":case "submit":break;default:return a.value}return null}function ga(a){var b=[],c=a.elements,d=c.length,e,f;for(e=0;e<d;e++)a=c[e],f=gfv(a),f!==null&&(b[a.name]=f);return b}function au(a){var b=[],c=0,d;for(d in a)d!==""&&(b[c++]=d+="="+escape(a[d]));return b.join("&")}
function ru(a,b){var c,d=b.split("&"),a=a.replace(/\?/,"?&");for(c=0;c<d.length;c++){var e=d[c],f=e.indexOf("=");f>0&&(f=e.substr(0,f+1),f=a.indexOf("&"+f),f>0?a=a.substring(0,f+1)+e+a.substring(f+1):a+="&"+e)}return a.replace(/\?\&/,"?")}function hu(a){return a.replace(/\&/,"&amp;")}function aau(a){it(a.elements,function(a){a.setAttribute("autocomplete","off")})}function dau(a){it(a.elements,function(a){a.removeAttribute("autocomplete")})}sem_a={};
function sem(a,b){var c=a.name,d;sem_a[c]!=b&&(sem_a[c]=b,d=gf("e"+c),c=gf(c),d&&(ih(d,b),ac(d,"errmark",b)),c&&ac(c,"errf",b))}function jsav(a,b){a+="&"+au(ga(b));jcb(a,function(a){var b="Some error occured - was not able to save";a.match(/JS:/)&&(b="Please wait - reloading page now",location.reload());iH("jcdiv",b)})}menact=null;men={};function PU(a){this.n=a;this.s=0;PU.p[PU.p.length]=this}PU.p=[];PU.C=function(a){it(PU.p,function(b){b!=a&&b.k()})};
PU.prototype.i=function(a){var b=this.e,c=1;it(a,function(a){a==b&&(c=0)});c&&dt()+this.s>200&&this.k()};var trkclk=Mr()<0.2;
ael(window,"click",function(a){for(var b=ev(a),a=b.s,a=b.e,a=a.target||a.currentTarget||a.relatedTarget||a.fromElement||a.srcElement,c=[],b=a;b;){var d=b.parentNode;c[c.length]=b;b=d}it(PU.p,function(a){a.s&&a.i(c)});if(a&&trkclk&&((b=a.href)||(b=a.type=="submit"?"submit":c[1].href),b)){var e="";c.pop();c.pop();it(c,function(a){var b=a.tagName;b&&(e=b+":"+a.id+";"+a.className+">"+e)});e=window.location.pathname+">>"+e+">>"+b+">>"+a.innerHTML;document.cookie="LINKUSED="+escape(e)+";domain=.timeanddate.com;path=/"}});
PU.prototype.h=function(a){var b=gf(this.n);this.e=b;ih(b,a);this.o();return b};PU.prototype.d=function(a){var b=gf(this.n);this.e=b;b.appendChild(a);this.o();return b};PU.prototype.E=function(a){this.e=a;if(a=a.id)this.n=a};PU.prototype.y=function(){this.s=-dt()};PU.prototype.o=function(){this.y();PU.C(this);sd(this.e,2)};PU.prototype.k=function(){sd(this.e,0);this.s=0;this.c&&this.c()};PU.prototype.x=function(a){a&&a!=this.s||this.s>=0&&this.k()};
PU.prototype.z=function(a){var b=this,a=a||330,c=dt()+a;b.s=c;window.setTimeout(function(){b.x(c)},a+100)};PU.prototype.A=function(a,b,c){var a=ghj(a),d=this.h(a.h),e=ap(b);jp(e,d,b,c||0,1);ep(d,e);eval(a.j)};pM=new PU("po1");function mena(a,b){b.n=a;var c=a.indexOf("txt");if(c>0)b.N=a.slice(0,c);men[a]=b}function menh(a){var b=menact;if(b){var c=b.e.getElementsByTagName("li");if(c){var d=function(a,b){typeof a==="number"&&a>=0&&a<c.length&&ac(c[a],"h",b)};d(b.h,0);d(a,1);b.h=a}}}
function mech(a,b){if(b)if(a.f)a.f(a,b);else if(a.i.value=b.n,a.g&&b.U)wl(b.U);else{if(a.I){a.I.value=b.U;var c=fh[a.n];c.H=b.U;c.T=b.n}va(a.i.id,a.i)}pM.k()}function menc(a){var b=menact;b&&(a=b.a[a])&&mech(b,a)}function menfr(){var a=menact;if(a&&(a=a.a[0])&&a.U)return 1}function mmenc(){menfr()&&menc(0)}
function mens(a,b){function c(a,b,c,d){var e=a.a[b],h="";if(e.s===1)h+="<li class=mnd>&nbsp;";else{var i="";e.p&&(i=hu(ru(f,e.p)));if(e.u)i=e.u;c=(c=(c?"lr":"")+(d?" ls":""))?"class='"+c+"' ":"";d="h";e.s&&(d+=" asb");h+="<li onmouseover='pM.y()'"+(e.h?" class='"+d+"' ":"")+">";d=e.n+(e.d||"");e.c&&(d="<span class="+e.c+">"+d+"</span>");if(e.s!==2)if(i)d="<a "+c+"href='"+i+"'>"+d;else if(a.i||e.v)d="<a "+c+"href='javascript:menc("+b+")'>"+d;h+=d;e.x&&(h+="<span class=mnx>"+e.x+"</span>");h+="</a>"}h+=
"</li>";return h}var d=men[a];if(d){var e=ap(b),f=d.u?d.u.replace(/\&amp\;/g,"&"):"/",g=0,h=d.c||"mn",j=d.C||h,h="<div class="+h+" onmouseout='pM.z()'>",n=d.a.length,i=d.r,l=0,m=i&&i<n,p=1;m?(p=Mf((n+i-1)/i),h+="<table><tr>"):i=n;for(;p--;){l+=i;for(var o="<ul class="+j+">";g<n&&g<l;g++)o+=c(d,g,p,g+1>=l);o+="</ul>";h+=m?"<td valign=top>"+o+"</td>":o}m&&(h+="</tr></table>");menact=d;g=pM.h(h);d.e=g;if(d.i&&(g.style.width="",j=d.i.offsetWidth,g.offsetWidth<j&&es(g,{w:j}),d.N))d.I=d.i.form[d.N];jp(e,
g,b,typeof d.j!="undefined"?d.j:-1,1);d.C=="asu"&&(e.x-=2,e.y+=5);d=b.offsetWidth;j=g.offsetWidth;j<d||d>350?es(g.firstChild,{w:d}):j>d&&j>350&&es(g.firstChild,{w:300});ep(g,e)}}function mensk(a,b){mens(a,b)}getAC=function(){var a={};return function(b){var c=a[b];c||(c=new AC(b),a[b]=c);return c}}();function AC(a){this.t=a;this.c={};this.l=null;this.p="";this.f=null;this.h={}}
AC.prototype.C=function(a){var b=this,a=a.toLowerCase();return a=a.replace(/[^\020-\177]/g,function(a){var d=b.h[a];typeof d==="string"&&(a=d);return a})};
AC.prototype.B=function(a,b){var c=function(a,b){var c=a.indexOf(b);if(c<0)return 0;var d=b.length;if(c===0)return d;if(a.charCodeAt(c-1)<65)return d*0.9;var e=b.length;if(e<2)return 0;d*=(e+0.1)/(e+5);a=a.substr(0,c);return(c=a.match(/([\040-\077]+)/))?0.5*d/(1+c.length):0.1},d=function(a,b){var c=b.s;c+=c?" - "+b.c:b.c;a.a[a.a.length]={c:"ash",n:b.n,x:c,U:b.i,h:0,d:b.f?"<img height=16 width=16 class=fr alt=Flag src='"+b.f+"'>":""}},e={i:this.f.f,a:[],c:"as",C:"asu",g:0,j:0};if(!a)return e;if(this.f.s)e.g=
1;this.l=a;var f=a.length;if(f){var b=this.C(b),g=b.split(/\s+/),h=g.length,j,n=[],i;for(i=0;i<f;i++){var l=a[i],m=0,p=0;for(j=0;j<h;j++){var o=g[j],k=(l.o==o)*10+(l.a==o)*5,q=l.x.indexOf(" "+o)>=0;if(l.t.indexOf(o)>=0||l.e.indexOf(o)>=0||l.u.indexOf(o)>=0||q){var r=c(l.t,o)*10,s=c(l.e,o)*5,o=c(l.u,o)*4;q&&k<10&&(k=10+l.z);r>k&&(k=r);s>k&&(k=s);o>k&&(k=o)}k&&(p++,m+=k)}m>0&&(j=p/h,n[n.length]={s:(l.p*3+m)*j*j,c:l})}n.sort(function(a,b){return b.s-a.s});f=n.length;f>5&&(f>20&&(f=20),i=gsv(),c=po(this.f.f),
c=i.h-c.y,i=i.H-10,c<i&&(i=c),i=Mf((i-45)/36),f>i&&(f=i),f<3&&(f=3));if(f>0){c=f>5?5:f;h=n[0].s;l=h*0.7;m=h*0.2;j=1;p=0;for(i=1;i<f;i++){g=h;h=n[i].s;if(h<m){f=i;break}k=g-h;i<c&&k>j&&g>l&&(j=k,p=i)}if(p>3||j<1.2)p=0;if(p){for(i=0;i<p;i++)d(e,n[i].c,1);e.a[e.a.length]={s:1}}n=n.slice(p,f);f=n.length;n.sort(function(a,b){return a.c.n.localeCompare(b.c.n)});for(i=0;i<f;i++)d(e,n[i].c,0)}else e.a[0]={n:"No matches",s:2,h:0,c:"ash"};this.f.s&&(e.a[e.a.length]={u:"/worldclock/",n:"World Clock",s:100,h:1});
return e}};
AC.prototype.U=function(){var a=this,b=function(b){b&&(b.a.length===0&&(b.a[0]={n:"Loading...",s:2,c:"ash"}),ifsm(a.f,b))},c=function(c){var d;a.c[c]={};var e="/scripts/completion.php?query="+encodeURIComponent(c);a.f.x&&(e+="&xd="+a.f.x);jcb(e,function(e){var e=e.split("\n"),h=e.length,i=[],l;for(l=0;l<h;l++){var m;m=e[l].split("\t");m.length>7?m={i:m[0],p:m[1],o:m[2],a:m[3],n:m[4],t:a.C(m[4]),s:m[5],e:a.C(m[5]),c:m[6],u:a.C(m[6]),f:m[7],x:" "+m[8]+" ",z:m[9]-0}:(m[0]==="CONV"&&(a.h[m[1]]=m[2]),
m=void 0);m&&i.push(m)}a.c[c].d=i;d=a.B(i,c);b(d)})},d=function(){var b;b=a.p;var d=a.c[b];d?b=d.d?a.B(d.d,b):a.B(a.l,b):(c(b),b=a.B(a.l,b));return b},e;a.p.length>=2&&(e=d(),b(e));e||pM.k()};AC.prototype.A=function(a,b){this.f=a;b=b.replace(/^\s+/g,"").replace(/\s+$/g,"").replace(/\s+/," ");this.p=b.toLowerCase();this.U()};function ifsm(a,b){a.m=b;a.u=-1;mena(a.n,b);mens(a.n,a.f)}
function ifd(a){var b=a.f,c=b.value,d=a.n.indexOf("txt");if(d>0){var e=b.form[a.n.slice(0,d)];if(e){var f=":";if(a.H&&a.T){var g=a.T.toLowerCase();if(c.toLowerCase().indexOf(g)>=0)f=a.H}e.value=f}}if(a.e){var h=a.t,j=11,n={i:b,a:[]},b=function(a,b){var c=b=b.replace(/\D/g,""),e,f=2,g=0;a.i=1;if(h=="y")g=(new Date).getFullYear()-5,f=b.length,f>0&&(f<4&&(b+="1005".slice(f)),g=b.slice(0,4)-5),a.a=3999,f=4;if(h=="m")g=1,j=12,a.a=12,e=",Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(",");if(h==
"M")g=1,j=36,a.a=36,n.r=12;if(h=="d")g=1,j=31,a.a=31,n.r=10;g=lim(g,1,3989);if(h=="w")g=0,j=54,a.a=53,n.r=15;if(h=="i"||h=="s")g=0,j=60,a.i=0,a.a=59,n.r=10;if(h=="h"){g=0;j=24;a.i=0;a.a=23;n.r=12;e=[];for(d=0;d<j;d++)e[d]=(d+11)%12+1+(d<12?"am":"pm")}for(d=0;d<j;d++){var q=e?" - "+e[g]:"";n.a[n.a.length]={n:pf(g,f),d:q,h:c==g};g++}};h.length==1&&(b(a,c),ifsm(a,n));if(h.length==2)a.l=1,a.o||h=="ci"&&getAC(h).A(a,c)}}function ifku(a){return ifd(a)}
function ifpd(a){a.preventDefault&&a.preventDefault();a.returnValue=!1}
function ifkd(a,b){var c,d=a.f,e,f=!0;c=(e=window.event)?e.keyCode:b.which;var g=a.u,h=a.m,j=a.l&&h;e=0;if(c==27)a.e=0,pM.k();c==38&&(e=-1);c==40&&(e=1);if(e)if(j){f=h.a.length-1;for(c=0;c<3;c++)if(g==-1?(a.o=d.value,g=e>0?0:f):g+=e,g>f&&(g=-1),g==-1||!h.a[g].s)break;d.value=g>=0?h.a[g].n:a.o;if(g<0)a.o=null;a.u=g;menh(g);return!1}else{if(g=d.value-0,g>=0&&(g+=e),a=fh[d.name],!a||!a.a||a.i<=g&&a.a>=g)d.value=g,f=!1}else if(c==13){if(g>=0&&j)return mech(h,h.a[g]),ifpd(b),!1}else a.o=null;ifd(a);return f}
function ifs(a){var b=a.u;return a.s&&b>=0?!1:!0}function ifcb(a){pM.z(50);a.getAttribute("tad-va")&&va(a.name,a)}function ifc(a,b,c,d){var e=a.name,f=fh[e];if(!f){f={n:e,f:a,t:b};fh[e]=f;b=e.indexOf("txt");if(b>0&&(e=e.slice(0,b),e=a.form[e]))f.H=e.value,f.T=a.value;oael(a,"keydown",function(a){ifkd(f,a)},0);oael(a,"keyup",function(a){ifku(f,a)},0);oael(a,"blur",function(b){ifcb(a,f,b)},0);if(c)f.s=1,oael(a.form,"submit",function(){return ifs(f)});if(d)f.x=d}f.e=1;return ifd(f)}
function ofs(a,b){var c=0,d,e,f=window,g="directories=no,location=no,menubar=no,resizable=yes,scrollbars=no,status=no,toolbar=no";if(e=f.screen)c=e.availHeight-30,d=e.availWidth-10;b?(g+=",left=0,screenX=0,top=0,screenY=0,fullscreen=yes",c&&(g+=",height="+c+",innerHeight="+c+",width="+d+",innerWidth="+d)):g+=",height=180,width=320";if(f.open(a.href,"_blank",g))return!1;alert("Could not open the popup-window, maybe there is a popup-blocker installed");b&&c&&(f.moveTo(0,0),f.resizeTo(d,c));return!0}
function jco(a,b,c,d){phg(b,b,function(b){pM.A('<table id=CB><thead><tr><td id=CT><a href="javascript:jcc()"><img class=fr src="../images/x3.png" alt=close width=18 height=18></a><div class=tc><strong>'+c+"</strong></div></td></tr><tr><td id=jcdiv>"+b+"</td></tr></table>",a,d)});return!1}function jcc(){pM.k()}function ges(a){return Mf(a*0.001)}
TO={co:{},e:0,f:0,j:0,J:0,p:0,s:0,t:"",z:1E3,Z:0,y:-1,C:[],gco:function(a){return TO.co[a]},dt:function(){return dt()+this.j},aC:function(a){a&&(this.C[this.C.length]=a)},S:function(a){var a=a?"&r="+a:"",b=dt(),c=this;jcb("/scripts/ts.php?ut="+b+"&cb="+Mr()+a,function(a){var e=dt(),e=(b+e)/2;c.j=Mf(parseFloat(a)*1E3-e);c.y=e-b+50;c.U();iH("ref","At time of loading, accuracy was within "+Math.round(c.y)/1E3+" seconds")})},Y:function(a){var b=this;b.s++<40&&(a+="_"+b.s,window.setTimeout(function(){b.S(a)},
2500))},R:function(a,b,c){var d="p"+b;if(a[d]!==c&&(a[d]=c,d=a[b]))if(ih(d,c),a=a.E)for(var e in a)d=a[e],this.R(d,b,c)},tO:function(a,b){var c=a.t,d=null,e;for(e=0;e<c.length;e++){var f=c[e];if(f.t>b)break;d=f;if(e)d.C=e}return!d?{a:"",o:0}:d},gF:function(a,b,c){var d=cks[a],a=this.tO(d,ges(b)),b=new Date(b.getTime()+a.o*1E3),b=d.f(b);c&&a.a&&(b+=" "+a.a);return b},U:function(){var a,b,c,d,e=[],f=this,g=f.dt(),h=f.p;f.p=g;if(ges(g)>et)rf("tz1","Will refresh in 10 seconds",10,0);else{if(h){h=g-h;
if(f.f>g){rf("tz1","Clock has gone backward - will refresh soon",7,0);return}h>3E4&&(d="f");h<-25&&(d="b");if(d){f.Y(d+h);return}}else f.f=g;f.J&&(g+=f.J);d=f.Z?g*0.001:ges(g);if(d!=f.e)for(a in f.e=d,it(f.C,function(a){a(g)}),cks){h=cks[a];b=f.tO(h,d);c=b.o;var j=b.a,n=b.d;b=b.C;if(c!==""&&h.c){var i=h.c,l=ges(i.t-g+999);i.z&&l<0&&(l=0);if(l!=i.p)i.f?ih(i.f1,i.f(l)):(l<0&&i.p>=0&&(ih(i.u1,"since"),ih(i.u2,"since")),i.p=l,l<0&&(l=-l),it(i.l,function(a){var b=a.f,c=Mf(l/b.f);b.m&&(c%=b.m);f.R(a,"n1",
c);f.R(a,"n2",a.u[c!=1?1:0])}))}if(c!==""){i=new Date((d+c)*1E3);if(h.p){h.p(h,i,a,h);var m=h.E;if(m)for(var p in m)h.p(m[p],i,p,h)}h.d1&&(f.R(h,"d1",h.f(i)),h.u&&(c=(Mf((d+c)/86400)+4)%7,e[c]=(e[c]||0)+h.C,window.dsts&&(f.R(h,"d3",n?dsts:""),e[7]=(e[7]||0)+h.C*(n||0))));h.s&&h.s.f(h.s,i,h.g);f.R(h,"d2",j);if(h.d&&(b>0&&rf("tz1","Page will be refreshed soon",30,300),j=i.getUTCDate(),h.d!=j))rf("da1","Page will be refreshed soon",10,150),iH("da2","Page will be refreshed soon"),h.d=j}}if(window.updwds&&
e.length&&(a=e.join(","),a!=f.t)){f.t=a;for(c=0;c<8;c++)if(a=e[c]||0,p=gf("smwd"+c))sd(p,a?1:0),iH("smwi"+c,updwds(a))}g=f.dt();setTimeout(function(){f.U()},f.z-g%f.z)}},icks:function(a){function b(a,b,c){function d(a,b){var c=-(Mf(b)%16)*e+"px",h=-Mf(b/16)*e+"px";a.style.backgroundPosition=c+" "+h}var e=c.s,b=ges(b.getTime());d(a.h,61+(b+450)%43200/900);d(a.m,1+b%3600/60);d(a.s,109+b%60)}function c(a,b,c){function d(a,b){k.beginPath();k.moveTo(a,0);k.lineTo(b,0);k.stroke()}function e(a,b,c,f,h){k.save();
k.lineWidth=a;if(h)k.strokeStyle=h;k.rotate(b*q/30);d(-c*o,f*o);k.restore()}var f=c.s,c=f>40,g=f<100,o=f/2,k=a.c,q=Math.PI;k.save();k.clearRect(0,0,f,f);k.translate(o,o);k.rotate(-q/2);k.lineCap="butt";if(g){k.beginPath();k.arc(0,0,o-2,0,q*2,!0);k.fillStyle=c?"#fff":"#fff";k.fill();k.lineWidth=c?4:1;k.strokeStyle=c?"#353535":"#065947";k.stroke();f=c?0.76:0.7;for(a=0;a<60;a+=5)k.lineWidth=c?a%15?2:4:1,d((o-1)*0.985,o*f),k.rotate(q/6)}k.lineCap="round";f=ges(b.getTime());b=f%60;a=f/60%60;f/=720;c?(e(2,
f,0.14,0.46,"#000"),e(1.5,a,0.14,0.76,"#000"),e(1,b,0.28,0.76,"#e00f21")):(e(1,f,0,0.5,"#065947"),e(1,a,0,0.9,"#065947"));k.restore()}function d(a){var d=cE("canvas"),e=a.s=a.s||56;if(d&&d.getContext){a.s=e;d.setAttribute("width",e);d.setAttribute("height",e);if(a.c)d.className=a.c;d.className+=" clk";return{f:c,e:d,c:d.getContext("2d")}}else{var f=function(a){var b=cE("div"),c=b.style;c.background="url(http://c.tadst.com/gfx/canvas/nclk"+e+".png?1)";es(b,{w:e,h:e});if(a)c.position="relative",a.appendChild(b);
return b},d=f(),g=f(d),m=f(g),f=f(m);if(a.c)d.className=a.c;d.className+=" clkimg";return{f:b,e:d,s:f,m:g,h:m}}}var e,f=[{n:"s2",f:1},{n:"m2",f:60},{n:"h2",f:3600},{n:"d2",f:86400},{n:"w2",f:604800},{n:"s1",f:1,m:60},{n:"m1",f:60,m:60},{n:"h1",f:3600,m:24},{n:"d1",f:86400},{n:"dw1",f:86400,m:7},{n:"w1",f:604800}],g=function(a,b){TO.co[a]=b;b.d1=gf(a);b.d2=gf(a+"a");b.d3=gf(a+"s");if(b.g){var c=d(b.g);if(c)b.s=c,b.d1.parentNode.insertBefore(c.e,b.d1)}b.u=a.charAt(0)=="p";var g=b.c;if(g){var l={s:["second",
"seconds"],m:["minute","minutes"],h:["hour","hours"],d:["day","days"],w:["week","weeks"]};g.f1=gf(a+"_f1");g.u1=gf(a+"_u1");g.u2=gf(a+"_u2");g.l=[];it(f,function(b,c){var b=f[c],d=a+"_"+b.n;g.l[c]={f:b,n1:gf(d),n2:gf(d+"t"),u:l[b.n.charAt(0)]}})}b.C=1;if(b.e)c=b.e.split(","),b.E={},it(c,function(a){a=a.replace(/^(\d)/,"p$1");b.E[a]={};b.C++}),e(b.E)};e=function(a){for(var b in a)g(b,a[b])};e(a)},init:function(){var a=window.cks;typeof a=="object"&&(this.icks(a),window.TO_noupd||this.S())}};elh={};
elc={};fh={};window.TD||(TD={});function ael(a,b,c,d){if(a){if(typeof a=="string"&&(a=gf(a),!a))return;a.addEventListener?a.addEventListener(b,c,d):a.attachEvent&&a.attachEvent("on"+b,c)}}function aelw(a,b,c){ael(window,a,b,c)}function oael(a,b,c,d){var e=a.id;if(!e)e=a.name;if(!e)e=a.href;e=b+":"+e;elh[e]||(elh[e]=1,ael(a,b,c,d))}function aelc(a,b){ael(a,"click",function(c){c=ev(c);b(a,c);ifpd(c.e);return!1},!0)}blo=-1;
function bls(a){var b=gf("FBD");sd(b,blo);if(blo<0)a=a.href,a.match(/\.html/)?a=a.replace(".h","-frame.h"):a.match(/\?/)?a=a.replace("?","-frame?"):a+="-frame",ih(b,"<iframe id=FBF src='"+a+"' width=980 height=500 frameborder=0>webmaster@timeanddate.com</iframe>");blo=!blo;return!1}function blc(){blo=0;bls();blo=-1}function ev(a){var b={};a?b.k=a.which:(a=window.event,b.k=a.keyCode);if(b.e=a)b.s=a.target||a.srcElement;return b}
function bli(){var a=wl();if(a){var b="?url="+a.pathname;(a=a.search)&&(b+=encodeURIComponent(a));a=function(a,b,c,g){a&&document.write('<a href="'+a+'"  alt="'+c+'"'+g+">"+b+"</a> | ")};a("/information/feedback.html"+b,"Feedback","Send feedback to us",' onclick="return bls(this)"');if(b.length>8){var c="/createshort.html";c+=b;a(c,"Short URL","Create a short URL to this page","")}else a("/information/linkpolicy.html","Link policy","About linking","")}}
function ott(a,b){oael(a,"mouseout",function(){pM.z()});var c=b;ttt&&ttt[b]&&(c=ttt[b]);var c="<div id=ttb onmouseover='pM.y()' onmouseout='pM.z()'>"+c+"</div>",d=ap(a),c=pM.h(c);jp(d,c,a,-1,0);ep(c,d)}function calp(a,b){a.className.indexOf("disabled")>=0||phg("calp","/scripts/field/calpop",function(c){pM.A(c,a);CPop.init(pM,b,document.f)})}
function vad(a,b,c){var d=0,e=[],f=function(a,b,c){if(a){var f=gfv(a),i=f.replace(/[\s\.\-\,]/g,"");if(i!=f)a.value=i;i!==""&&i!==null&&(i-=0,i>=b&&i<=c&&(e.push(i),d++))}};f(a,1,3999);f(b,1,12);f(c,1,31);if(d==3){a=e[0];b=e[1];c=e[2];if(a>1925){f=31;if(b==4||b==6||b==9||b==11)f=30;b==2&&(f=28+(a%4==0)-(a%100==0)+(a%400==0));if(c>f)return null}f=new Date(0);f.setUTCFullYear(a);f.setUTCMonth(b-1);f.setUTCDate(c);return f}return null}
function vat(a,b,c){function d(){ac(c,"error",0)}function e(){d();ac(c,"error",1)}function f(a,b){if(n<a)return e(),1;if(n>b)return e(),1;d()}var g=b.match(/(\w)(\d+)/),h,j=c.value,n=j.replace(/[\s\.\-\,]/g,"");if(n){if(n!=j)c.value=n;var i;if(a=="date"&&(g?(i=g[1],h=g[2],h=["y"+h,"m"+h,"d"+h]):(b=="year"&&(i="y"),b=="month"&&(i="m"),b=="day"&&(i="d"),i&&(h=["year","month","day"])),h)){if(i=="y"&&f(1,3999))return;if(i=="m"&&f(1,12))return;if(i=="d"&&f(1,31))return;var l=[],m=[];it(h,function(a){if(a=
gf(a)){var b=a.value;b!==null&&b!==""&&(l.push(b-0),m.push(a))}});if(l.length==3){var c=m[2],j=l[0],p=l[1],o=l[2];if(j>1925){var k=31;if(p==4||p==6||p==9||p==11)k=30;p==2&&(k=28+(j%4==0)-(j%100==0)+(j%400==0));if(o>k){e();return}}}d()}a=="time"&&(g?(i=g[1],h=g[2],h=["h"+h,"i"+h,"s"+h]):(b=="hour"&&(i="h"),b=="min"&&(i="i"),b=="sec"&&(i="s"),i&&(h=["hour","min","sec"])),h&&(i=="h"&&f(0,23),i=="i"&&f(0,59),i=="s"&&f(0,59)))}else d()}
function va(a,b){if(a){if(b){var c=b.getAttribute("tad-va");c&&vat(c,a,b)}(c=elc[a])&&c()}}function elca(a,b){elc[a]=b}function abrd(a,b){return'<a href="javascript:modph()" class="close" title="Close"><img alt="close" src="../images/popup-close.png"/></a><h1 class=title>'+a+"</h1>"+b}
function modps(a, b, c) { var a = ghj(a), c = "alert(a.h);<div class=modal><div class=modal-dialog><div class=modal-content><div class=modal-header><input type=button class=close onclick=modph() />\u00d7;<h2 class=modal-title>" + (c || "Info") + "</h2></div>" + a.h + "</div></div></div>", d = gf("mpo"); ih(d, c); eval(a.j); oael(d, "click", function (a) { a = ev(a).s; (a == d || a.parentNode == d) && modph() }); oael(window, "keydown", function (a) { ev(a).k == 27 && modph() }); sd(d, 2) } function modpop(a, b, c) { a && jcb(a, function (a) { modps(a, b, c) }); return !1 }

function modph(a){ alert('prijat');gfv(); he("mpo",0);typeof a==="function"&&a()}function popad(a,b,c){var d=wl();c+="?ref="+escape(d.pathname+d.search);aelc(a,function(){modpop(c,1,b)})}function popadlogin(a){popad(a,"Login","/custom/loginframe.html")}function popadreg(a){popad(a,"Register a new account","/custom/createframe.html")}function hsl(a,b){if(a){a.style.overflow="hidden";var c=gcs(a,"height"),d=1,e=function(){c-=d;d++;c>0?(es(a,{h:c}),window.setTimeout(e,20)):sd(a,0)};window.setTimeout(e,b)}}
switching=function(){function a(a){c=a;it(b,function(a){var b=a==c;ac(gf("ec"+a),"active",b);sd(gf(a),b)})}var b=arguments,c=b[0];it(b,function(b){aelc("ec"+b,function(){a(b)})});a(c)};function extfield(a,b){var c;TD.C=function(b,c){var f=document.f[a],g=f.options;if(g){var h=g.length;g[h]=new Option(c,b);f.selectedIndex=h}else if(f.value=b,g=document.f[a+"txt"])g.value=c;va(a,f)};modpop("/scripts/field/"+b,1,"Select city")}function extlocs(a,b){if(b)TD.sh=1;extfield(a,"location","Select city")}
function exttzs(a,b){if(b)TD.sh=1;extfield(a,"timezone","Select time zone")}function pn(){return window.performance&&window.performance.now?window.performance.now():+new Date}var raf=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){window.setTimeout(function(){a(pn())},1E3/60)}}();
(function(){ael(window,"load",function(){var a=gf("bx-index");a&&(a=gebtn("a",a),it(a,function(a){a.hash!==""&&aelc(a,function(){siv(gf(a.hash.replace("#","")),!0)})}))})})();
function main(){popadlogin("poplogin");popadreg("popreg");popad("popin","You are logged in","/custom/loggedinframe.html");aelc("popout",function(){document.cookie="TIMEANDDATE_LOGIN=;domain=.timeanddate.com;path=/;expires="+(new Date(0)).toGMTString();wl().reload()});hsl(gf("svbx"),3E3);var a=function(a){aelc(gf("ftbx"+a),function(){var b;for(b=0;b<4;b++){var e=gf("ftbx"+b);if(e)he("feat"+b,b==a),e.className=b===a?"active":""}})},b;for(b=0;b<4;b++)a(b);scrlr=function(){function a(b,c){e.push({e:b,
c:c})}function b(){var a=(window.pageYOffset||window.document.documentElement.scrollTop)>f;it(e,function(b){ac(b.e,b.c,a)})}var e=[],f;return{init:function(e){a(e,"sticky");f=e.offsetTop;ael(window,"scroll",b);b()},addEle:a,to:b}}();(a=gf("nav"))&&scrlr.init(a);TO.init()}
(function(){function a(a){sd(a,1);ael(a,"mouseover",function(){var g=c[a.getAttribute("data-social")];g&&(b(g.src,g.id),clearTimeout(f),it(d,function(b){a!==b&&ac(b,"hover",0)}),ac(a,"hover",1),e=a)});ael(a,"mouseout",function(){f=setTimeout(function(){g||ac(a,"hover",0)},2E3)});d.push(a)}function b(a,b){var c,d=gebtn("script")[0];gf(b)||(c=cE("script",{id:b,src:a}),d.parentNode.insertBefore(c,d))}var c={facebook:{src:"//connect.facebook.net/en_GB/all.js#xfbml=1&appId=119413198130333",id:"facebook-jssdk"},
twitter:{src:"//platform.twitter.com/widgets.js",id:"twitter-wjs"},google:{src:"//apis.google.com/js/plusone.js",id:"google-js"}},d=[],e,f,g=!1;window.gpluso=function(){g=!0;clearTimeout(f)};window.gplusc=function(){g=!1;ac(e,"hover",0)};it(gebc("social"),function(b){a(b)})})();aelw("load",main);
